name        : perl-io-socket-ssl
version     : 2.012
release     : 4
source      :
    - http://search.cpan.org/CPAN/authors/id/S/SU/SULLR/IO-Socket-SSL-2.012.tar.gz : 02bd7f17ceb492e396eca6627f50aaa2a3ddfcb5bfa3889ddf145383b0b179d9
homepage    : http://search.cpan.org/~behroozi/IO-Socket-SSL-0.97/SSL.pm
license     :
    - Artistic-Perl-1.0
summary     : IO::Socket::SSL -- Nearly transparent SSL encapsulation for IO::Socket::INET
component   : programming.perl
description : |
    IO::Socket::SSL -- Nearly transparent SSL encapsulation for IO::Socket::INET
setup      : |
    # Stop prompts at build time
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
