name       : perl-io-socket-ssl
version    : '2.083'
release    : 16
source     :
    - https://cpan.metacpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.083.tar.gz : 904ef28765440a97d8a9a0df597f8c3d7f3cb0a053d1b082c10bed03bc802069
homepage   : https://metacpan.org/dist/IO-Socket-SSL
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : IO::Socket::SSL -- Nearly transparent SSL encapsulation for IO::Socket::INET
description: |
    IO::Socket::SSL makes using SSL/TLS much easier by wrapping the necessary functionality into the familiar IO::Socket interface and providing secure defaults whenever possible. This way, existing applications can be made SSL-aware without much effort, at least if you do blocking I/O and don't use select or poll.
builddeps  :
    - perl-mozilla-ca
    - perl-net-ssleay
rundeps    :
    - perl-mozilla-ca
    - perl-net-ssleay
setup      : |
    # Stop prompts at build time
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
