name       : perl-io-socket-ssl
version    : '2.060'
release    : 14
source     :
    - https://cpan.metacpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.060.tar.gz : fb5b2877ac5b686a5d7b8dd71cf5464ffe75d10c32047b5570674870e46b1b8c
homepage   : https://github.com/noxxi/p5-io-socket-ssl
license    : Artistic-Perl-1.0
summary    : IO::Socket::SSL -- Nearly transparent SSL encapsulation for IO::Socket::INET
component  : programming.perl
description: |
    IO::Socket::SSL -- Nearly transparent SSL encapsulation for IO::Socket::INET
builddeps  :
    - perl-mozilla-ca
    - perl-net-ssleay
rundeps    :
    - perl-mozilla-ca
    - perl-net-ssleay
setup      : |
    # Stop prompts at build time
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
