name       : perl-io-socket-ssl
version    : '2.058'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/S/SU/SULLR/IO-Socket-SSL-2.058.tar.gz : 746cd17c292cfc206b394497a060b0582d0b06a1040e6bb27e6530d56786e40b
homepage   : https://github.com/noxxi/p5-io-socket-ssl
license    : Artistic-Perl-1.0
summary    : IO::Socket::SSL -- Nearly transparent SSL encapsulation for IO::Socket::INET
component  : programming.perl
description: |
    IO::Socket::SSL -- Nearly transparent SSL encapsulation for IO::Socket::INET
builddeps  :
    - perl-net-ssleay
rundeps    :
    - perl-net-ssleay
setup      : |
    # Stop prompts at build time
    %perl_setup < /dev/null
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
